name: heyda.nl
favicon: null
layout_spectrum: 0.99347
typography_spectrum: 0.18239
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfcff'
    - '#332e15'
    - '#f6bd58'
    - '#83662f'
    - '#0088c1'
  brandStrength: 0.0625
  lightness: 0.8326147766783834
  saturation: 0.31280189123936
  rhythmicContrast: 0.8423057121690363
purpose: []
